### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by galindus**
Use base image with compatible torch cuda version (11.7)

### CODE REVIEW

**Comment by justinmerrell** [comment]
@zhl146 From my tests with the runtime image, I can confirm that 11.7 is more reliable, with 11.7 being on their stable list. 

https://pytorch.org/blog/deprecation-cuda-python-support/

**Comment by zhl146** [comment]
Will update this soon - waiting because we have a ton of machines stuck on 11.6 :(

**Comment by justinmerrell** [comment]
@zhl146 I believe the changes in this PR are backwards compatible

**Comment by justinmerrell** [comment]
Containers updated

**Pull request closed without merging**
